### ISSUE TITLE
Venn Diagram - Pull out common taxa

### ISSUE THREAD

**Issue by gcuster1991** [MayaGans/CoreMicro#17]
Pull out taxa that are found in all methods

**Comment by MayaGans** [comment]
list:

```
[1][1] Taxa Name 
[1][2] Number Included
[1][3] Methods of inclusion
```

**Comment by MayaGans** [comment]
Eventually @gcuster1991 needs to add `common_core()` to vignette

**Comment by gcuster1991** [comment]
Eventually @MayaGans 'common_core()' can be subset by number of methods

**Comment by MayaGans** [comment]
`threshhold` argument that filters the list based on [1][2]
